name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: sungwon-097/account-info-app
          stage: main
          yaml: >
            name: account-info-app-client

            app: web

            options:
              docbase: /build
              nodeversion: "18"
              spa: false
              buildenv:
                - name: REACT_APP_CLIENTID
                  value: 2d720bca-aaea-46b6-9943-274bb39a5f8a
                - name: REACT_APP_REDIRECT_URI
                  value: https://web-account-info-app-client-6g2llf5d1j9b.sel3.cloudtype.app
                - name: REACT_APP_SCOPE
                  value: login inquiry transfer
                - name: REACT_APP_STATE
                  value: b80BLsfigm9OokPTjy03elbJqRHOfGSY
                - name: REACT_APP_AUTH_TYPE
                  value: "0"
                - name: REACT_APP_TEST_API_URL
                  value: https://testapi.openbanking.or.kr/oauth/2.0/authorize
                - name: REACT_APP_PROXY
                  value: https://port-0-account-info-app-server-6g2llf5d1j9b.sel3.cloudtype.app
              install: npm install --force
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: react
